# This file was generated by GoReleaser. DO NOT EDIT.
cask "s3s" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "59099c25a5494a4ebea3cc93d719e8e2a1746f830614332f13877e48f33a1da1"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a052b62911da89c357cd49e188b7f1fc3dc7af805853ba0865c9fc65b584bc4e"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc36d4dac034d620a657e6a5017c813a57a77a12c7af3bffa4344215e5b2b1ac"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7856cc3c961174cdd4d71456144bbdb09e496ac6732093985fbdb68c76b9363b"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Linux_arm64.tar.gz"
    end
  end

  name "s3s"
  desc "Read-only, keyboard-driven TUI for browsing S3-compatible object storage."
  homepage "https://github.com/danchupin/s3s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s3s"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/s3s"]
    end
  end

  # No zap stanza required

end
