# This file was generated by GoReleaser. DO NOT EDIT.
cask "s3s" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "576c86eaa4dbc73c9e45592873e4ac7b4d7736f49bd81e8f79e8783502de8468"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "40bab66c7c78f25e437d5d97f0f7e5d7fc8db9814324c5676998082f0ce4c4dd"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a937e277831e0f4f0a26d791e3159a859335a3d2eba03637e40858b4e23607b7"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ff705b2e1184e972163da9d3876daa88e0642906631a7e647c120a4ec250fe8c"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Linux_arm64.tar.gz"
    end
  end

  name "s3s"
  desc "Read-only, keyboard-driven TUI for browsing S3-compatible object storage."
  homepage "https://github.com/danchupin/s3s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s3s"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/s3s"]
    end
  end

  # No zap stanza required

end
