# This file was generated by GoReleaser. DO NOT EDIT.
cask "s3s" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d344e742604e3eea14ab37437d3427beac7582e141243201c6fcd32037d58c85"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "41f0ab5264b030091e9ba54a213fe007ed8332f9382a04df9a2dbee7717ad712"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8533b85c62c0aad83ec402ea957e1a98bfd62c5db75116e2d067af1472e358d"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "581a6d98c391206287619b9d5174679b5a9a369876b7d79c35dbe637787bc0da"
      url "https://github.com/danchupin/s3s/releases/download/v#{version}/s3s_Linux_arm64.tar.gz"
    end
  end

  name "s3s"
  desc "Read-only, keyboard-driven TUI for browsing S3-compatible object storage."
  homepage "https://github.com/danchupin/s3s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "s3s"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/s3s"]
    end
  end

  # No zap stanza required

end
